create table if not exists public.dog_badges (
  id bigint generated by default as identity primary key,
  dog_id uuid not null references public.dogs(id) on delete cascade,
  badge_id text not null,
  badge_type text not null default 'monthly'
    check (badge_type in ('monthly', 'mileage', 'limited')),
  period_key text not null default to_char(now() at time zone 'Australia/Sydney', 'YYYY-MM')
    check (period_key = 'permanent' or period_key ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  earned_at timestamptz not null default now(),
  unique (dog_id, badge_id, period_key)
);

create index if not exists dog_badges_dog_period_idx
on public.dog_badges (dog_id, period_key, earned_at desc);

alter table public.dog_badges enable row level security;

create policy "Owners can view their dog badges"
on public.dog_badges for select
to authenticated
using (exists (
  select 1 from public.dogs
  where dogs.id = dog_badges.dog_id
    and dogs.owner_id = (select auth.uid())
));

create policy "Owners can earn badges for their dogs"
on public.dog_badges for insert
to authenticated
with check (exists (
  select 1 from public.dogs
  where dogs.id = dog_badges.dog_id
    and dogs.owner_id = (select auth.uid())
));
