create table if not exists public.dog_badges (
  id bigint generated by default as identity primary key,
  dog_id uuid not null references public.dogs(id) on delete cascade,
  badge_id text not null,
  earned_at timestamptz not null default now(),
  unique (dog_id, badge_id)
);

alter table public.dog_badges enable row level security;

create policy "Owners can view their dog badges"
on public.dog_badges for select
using (exists (
  select 1 from public.dogs
  where dogs.id = dog_badges.dog_id
    and dogs.owner_id = auth.uid()
));

create policy "Owners can earn badges for their dogs"
on public.dog_badges for insert
with check (exists (
  select 1 from public.dogs
  where dogs.id = dog_badges.dog_id
    and dogs.owner_id = auth.uid()
));
