-- Waltz exploration + Local Legend foundation
-- Run after dogs, walks, walk_dogs, dog_badges and activity_events exist.

-- ============================================================
-- 1. AREAS / NEIGHBOURHOOD UNLOCKS
-- ============================================================

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  area_key text not null unique,
  name text not null,
  region text,
  country_code text not null default 'AU',
  boundary_geojson jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.dog_area_unlocks (
  id bigint generated by default as identity primary key,
  dog_id uuid not null references public.dogs(id) on delete cascade,
  area_id bigint not null references public.areas(id) on delete cascade,
  first_walk_id bigint references public.walks(id) on delete set null,
  unlocked_at timestamptz not null default now(),
  unique (dog_id, area_id)
);

create index if not exists dog_area_unlocks_dog_idx
on public.dog_area_unlocks (dog_id, unlocked_at desc);

-- ============================================================
-- 2. SEGMENTS / LOCAL LEGENDS
-- ============================================================

create table if not exists public.segments (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  area_id bigint references public.areas(id) on delete set null,
  route_points jsonb not null default '[]'::jsonb,
  corridor_m integer not null default 40 check (corridor_m between 10 and 200),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- One matched completion of one segment by one dog on one walk.
create table if not exists public.dog_segment_efforts (
  id bigint generated by default as identity primary key,
  dog_id uuid not null references public.dogs(id) on delete cascade,
  segment_id bigint not null references public.segments(id) on delete cascade,
  walk_id bigint not null references public.walks(id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (dog_id, segment_id, walk_id)
);

create index if not exists dog_segment_efforts_segment_date_idx
on public.dog_segment_efforts (segment_id, completed_at desc);

create index if not exists dog_segment_efforts_dog_date_idx
on public.dog_segment_efforts (dog_id, completed_at desc);

-- Permanent record that a dog has become Local Legend of a segment at least once.
-- A dog can later lose the current crown, but this award remains for achievements.
create table if not exists public.dog_local_legend_awards (
  id bigint generated by default as identity primary key,
  dog_id uuid not null references public.dogs(id) on delete cascade,
  segment_id bigint not null references public.segments(id) on delete cascade,
  awarded_at timestamptz not null default now(),
  unique (dog_id, segment_id)
);

create index if not exists dog_local_legend_awards_dog_idx
on public.dog_local_legend_awards (dog_id, awarded_at desc);

-- ============================================================
-- 3. ACTIVITY EVENT TYPE
-- ============================================================

alter table public.activity_events
  drop constraint if exists activity_events_event_type_check;

alter table public.activity_events
  add constraint activity_events_event_type_check
  check (
    event_type in (
      'boop_received',
      'badge_earned',
      'shared_walk',
      'area_unlocked',
      'local_legend',
      'challenge_complete'
    )
  );

-- ============================================================
-- 4. AREA UNLOCK -> ACTIVITY + 10-AREA BADGE
-- ============================================================

create or replace function public.after_area_unlock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  unlocked_name text;
  unlock_count integer;
begin
  select name into unlocked_name
  from public.areas
  where id = new.area_id;

  insert into public.activity_events (
    dog_id,
    event_type,
    walk_id,
    metadata,
    created_at
  )
  values (
    new.dog_id,
    'area_unlocked',
    new.first_walk_id,
    jsonb_build_object(
      'area_id', new.area_id,
      'area_name', unlocked_name
    ),
    new.unlocked_at
  );

  select count(*) into unlock_count
  from public.dog_area_unlocks
  where dog_id = new.dog_id;

  if unlock_count >= 10 then
    insert into public.dog_badges (dog_id, badge_id)
    values (new.dog_id, 'urban-explorer')
    on conflict (dog_id, badge_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists area_unlock_activity_trigger
on public.dog_area_unlocks;

create trigger area_unlock_activity_trigger
after insert on public.dog_area_unlocks
for each row
execute function public.after_area_unlock();

-- ============================================================
-- 5. LOCAL LEGEND AWARD -> ACTIVITY + 10-CROWN BADGE
-- ============================================================

create or replace function public.after_local_legend_award()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  segment_name text;
  area_name text;
  crown_count integer;
begin
  select s.name, a.name
    into segment_name, area_name
  from public.segments s
  left join public.areas a on a.id = s.area_id
  where s.id = new.segment_id;

  insert into public.activity_events (
    dog_id,
    event_type,
    metadata,
    created_at
  )
  values (
    new.dog_id,
    'local_legend',
    jsonb_build_object(
      'segment_id', new.segment_id,
      'segment_name', segment_name,
      'area_name', area_name
    ),
    new.awarded_at
  );

  select count(*) into crown_count
  from public.dog_local_legend_awards
  where dog_id = new.dog_id;

  if crown_count >= 10 then
    insert into public.dog_badges (dog_id, badge_id)
    values (new.dog_id, 'local-royalty')
    on conflict (dog_id, badge_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists local_legend_activity_trigger
on public.dog_local_legend_awards;

create trigger local_legend_activity_trigger
after insert on public.dog_local_legend_awards
for each row
execute function public.after_local_legend_award();

-- ============================================================
-- 6. RLS / BASIC ACCESS
-- ============================================================

alter table public.areas enable row level security;
alter table public.segments enable row level security;
alter table public.dog_area_unlocks enable row level security;
alter table public.dog_segment_efforts enable row level security;
alter table public.dog_local_legend_awards enable row level security;

grant select on public.areas, public.segments to authenticated;
grant select, insert on public.dog_area_unlocks to authenticated;
grant select on public.dog_segment_efforts, public.dog_local_legend_awards to authenticated;

drop policy if exists "Authenticated users can see areas" on public.areas;
create policy "Authenticated users can see areas"
on public.areas for select to authenticated using (true);

drop policy if exists "Authenticated users can see segments" on public.segments;
create policy "Authenticated users can see segments"
on public.segments for select to authenticated using (true);

drop policy if exists "Authenticated users can see area unlocks" on public.dog_area_unlocks;
create policy "Authenticated users can see area unlocks"
on public.dog_area_unlocks for select to authenticated using (true);

drop policy if exists "Users can unlock areas for their own dogs" on public.dog_area_unlocks;
create policy "Users can unlock areas for their own dogs"
on public.dog_area_unlocks for insert to authenticated
with check (
  exists (
    select 1 from public.dogs d
    where d.id = dog_id
      and d.owner_id = auth.uid()
  )
);

drop policy if exists "Authenticated users can see segment efforts" on public.dog_segment_efforts;
create policy "Authenticated users can see segment efforts"
on public.dog_segment_efforts for select to authenticated using (true);

drop policy if exists "Authenticated users can see local legend awards" on public.dog_local_legend_awards;
create policy "Authenticated users can see local legend awards"
on public.dog_local_legend_awards for select to authenticated using (true);
