import { useEffect,useState } from "react";
import { Alert,Image,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { Dog as DogIcon,PawPrint } from "@sketchyicons/react-native";
import { createDog,deleteDog,updateDog,uploadDogAvatar } from "../services/dogs";
import { Dog } from "../types/dog";

type Props={visible:boolean;userId:string;dogs:Dog[];activeDogId:string;onClose:()=>void;onChanged:()=>Promise<void>|void;onSelect:(id:string)=>void};
export function DogManagerModal({visible,userId,dogs,activeDogId,onClose,onChanged,onSelect}:Props){
 const [editing,setEditing]=useState<Dog|null>(null),[adding,setAdding]=useState(false),[name,setName]=useState(""),[breed,setBreed]=useState(""),[profileLine,setProfileLine]=useState("Very good dog"),[day,setDay]=useState(""),[month,setMonth]=useState(""),[year,setYear]=useState(""),[photo,setPhoto]=useState<string|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!visible){setEditing(null);setAdding(false);setPhoto(null)}},[visible]);
 function edit(d:Dog){setEditing(d);setAdding(false);setName(d.name);setBreed(d.breed||"");setProfileLine(d.profile_line||"Very good dog");setDay(d.birth_day?String(d.birth_day):"");setMonth(d.birth_month?String(d.birth_month):"");setYear(String(d.birth_year));setPhoto(d.avatar_url)}
 function add(){setEditing(null);setAdding(true);setName("");setBreed("");setProfileLine("Very good dog");setDay("");setMonth("");setYear("");setPhoto(null)}
 async function pick(){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){Alert.alert("Photo permission needed","Allow photo access to choose a dog profile picture.");return}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],allowsEditing:true,aspect:[1,1],quality:.8});if(!r.canceled)setPhoto(r.assets[0].uri)}
 function birthday(){const y=Number(year),m=month.trim()?Number(month):null,d=day.trim()?Number(day):null;if(!Number.isInteger(y)||y<1980||y>new Date().getFullYear())return null;if(m!==null&&(!Number.isInteger(m)||m<1||m>12))return null;if(d!==null&&(!Number.isInteger(d)||d<1||d>31))return null;if(d!==null&&m===null)return null;if(m!==null&&d!==null){const test=new Date(y,m-1,d);if(test.getFullYear()!==y||test.getMonth()!==m-1||test.getDate()!==d)return null}return{y,m,d}}
 async function save(){if(!name.trim()){Alert.alert("Name needed","Every waltzing dog needs a name.");return}const dob=birthday();if(!dob){Alert.alert("Birthday check","Use DD / MM / YYYY. Year is required. Day and month are optional, but add a month if you add a day.");return}setBusy(true);try{if(editing){let avatar=editing.avatar_url;if(photo&&photo!==editing.avatar_url)avatar=await uploadDogAvatar(userId,editing.id,photo);await updateDog(editing.id,{name,breed,profileLine:profileLine.trim()||"Very good dog",avatarUrl:avatar,birthYear:dob.y,birthMonth:dob.m,birthDay:dob.d});}else{const dog=await createDog({ownerId:userId,name,birthYear:dob.y,birthMonth:dob.m,birthDay:dob.d,breed,profileLine:profileLine.trim()||"Very good dog"});if(photo){const avatar=await uploadDogAvatar(userId,dog.id,photo);await updateDog(dog.id,{name,breed,profileLine:profileLine.trim()||"Very good dog",avatarUrl:avatar,birthYear:dob.y,birthMonth:dob.m,birthDay:dob.d});}onSelect(dog.id)}await onChanged();setEditing(null);setAdding(false);}catch(e){Alert.alert("Couldn’t save",e instanceof Error?e.message:"Unknown error")}finally{setBusy(false)}}
 function confirmDelete(){if(!editing)return;if(dogs.length<=1){Alert.alert("Keep one walking buddy","Waltz needs at least one dog profile.");return}Alert.alert(`Delete ${editing.name}?`,`This removes ${editing.name}'s dog profile. Saved walk records are not deleted.`,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:async()=>{setBusy(true);try{const deletingId=editing.id;await deleteDog(deletingId);const replacement=dogs.find(d=>d.id!==deletingId);if(activeDogId===deletingId&&replacement)onSelect(replacement.id);await onChanged();setEditing(null);}catch(e){Alert.alert("Couldn’t delete",e instanceof Error?e.message:"Unknown error")}finally{setBusy(false)}}}])}
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.overlay}><View style={s.sheet}><View style={s.head}><Text style={s.title}>{editing?"Edit dog":adding?"Add another dog":"My dogs"}</Text><Pressable onPress={onClose}><Text style={s.close}>Done</Text></Pressable></View>{editing||adding?<ScrollView keyboardShouldPersistTaps="handled"><Pressable style={s.photo} onPress={pick}>{photo?<Image source={{uri:photo}} style={s.photoImage}/>:<DogIcon size={42} strokeWidth={2} color="#665D54"/>}<Text style={s.photoText}>{photo?"Change photo":"Add photo"}</Text></Pressable><Text style={s.label}>Name</Text><TextInput value={name} onChangeText={setName} style={s.input}/><Text style={s.label}>Profile line</Text><TextInput value={profileLine} onChangeText={setProfileLine} placeholder="Very good dog" maxLength={40} style={s.textInput}/><Text style={s.helper}>This is the little line shown under {name.trim()||"your dog"}'s name.</Text><Text style={s.label}>Birthday</Text><View style={s.dobRow}><View style={s.dobPart}><Text style={s.dobHint}>DD · optional</Text><TextInput value={day} onChangeText={setDay} keyboardType="number-pad" maxLength={2} placeholder="DD" style={s.input}/></View><Text style={s.slash}>/</Text><View style={s.dobPart}><Text style={s.dobHint}>MM · optional</Text><TextInput value={month} onChangeText={setMonth} keyboardType="number-pad" maxLength={2} placeholder="MM" style={s.input}/></View><Text style={s.slash}>/</Text><View style={s.yearPart}><Text style={s.dobHint}>YYYY · required</Text><TextInput value={year} onChangeText={setYear} keyboardType="number-pad" maxLength={4} placeholder="YYYY" style={s.input}/></View></View><Text style={s.label}>Breed</Text><TextInput value={breed} onChangeText={setBreed} placeholder="Optional" style={s.textInput}/><Pressable style={s.save} onPress={save} disabled={busy}><Text style={s.saveText}>{busy?"SAVING…":"SAVE"}</Text></Pressable>{editing&&<Pressable style={s.deleteButton} onPress={confirmDelete} disabled={busy}><Text style={s.deleteText}>Delete {editing.name}</Text></Pressable>}<Pressable onPress={()=>{setEditing(null);setAdding(false)}}><Text style={s.back}>‹ My dogs</Text></Pressable></ScrollView>:<><ScrollView>{dogs.map(d=><Pressable key={d.id} style={[s.dogRow,d.id===activeDogId&&s.activeRow]} onPress={()=>{onSelect(d.id);onClose()}}><View style={s.thumb}>{d.avatar_url?<Image source={{uri:d.avatar_url}} style={s.thumbImage}/>:<DogIcon size={29} strokeWidth={2} color="#665D54"/>}</View><View style={{flex:1}}><Text style={s.dogName}>{d.name}{d.id===activeDogId?"  ✓":""}</Text><Text style={s.breed}>{d.profile_line||"Very good dog"}</Text></View><Pressable onPress={()=>edit(d)} hitSlop={10}><Text style={s.edit}>Edit</Text></Pressable></Pressable>)}</ScrollView><Pressable style={s.add} onPress={add}><PawPrint size={20} strokeWidth={2} color="#596442"/><Text style={s.addText}>Add another dog</Text></Pressable></>}</View></View></Modal>
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(0,0,0,.28)",justifyContent:"flex-end"},sheet:{maxHeight:"82%",backgroundColor:"#FFFDF8",borderTopLeftRadius:30,borderTopRightRadius:30,padding:22,paddingBottom:36},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:18},title:{fontFamily:"Schoolbell_400Regular",fontSize:31,color:"#1D1A17"},close:{fontWeight:"800",color:"#78845C"},dogRow:{flexDirection:"row",alignItems:"center",gap:12,padding:12,borderRadius:20,marginBottom:8},activeRow:{backgroundColor:"#F3EDDF"},thumb:{width:54,height:54,borderRadius:27,backgroundColor:"#EEE5D7",alignItems:"center",justifyContent:"center",overflow:"hidden"},thumbImage:{width:"100%",height:"100%"},dogName:{fontSize:17,fontWeight:"800",color:"#302B26"},breed:{fontSize:11,color:"#82786E",marginTop:2},edit:{fontSize:12,fontWeight:"800",color:"#78845C"},add:{marginTop:8,minHeight:54,borderRadius:18,borderWidth:1,borderStyle:"dashed",borderColor:"#CFC5B7",flexDirection:"row",gap:8,alignItems:"center",justifyContent:"center"},addText:{fontWeight:"800",color:"#596442"},photo:{alignSelf:"center",width:112,height:112,borderRadius:56,backgroundColor:"#F1E7D7",alignItems:"center",justifyContent:"center",overflow:"hidden",marginBottom:20},photoImage:{width:"100%",height:"100%"},photoText:{position:"absolute",bottom:8,fontSize:10,fontWeight:"800",backgroundColor:"rgba(255,253,248,.8)",paddingHorizontal:7,paddingVertical:3,borderRadius:9},label:{fontSize:12,fontWeight:"800",color:"#655D54",marginTop:10,marginBottom:5},input:{height:50,borderRadius:15,backgroundColor:"#F5EEE4",paddingHorizontal:12,fontSize:16,color:"#211E1B",textAlign:"center"},textInput:{height:50,borderRadius:15,backgroundColor:"#F5EEE4",paddingHorizontal:14,fontSize:16,color:"#211E1B"},helper:{fontSize:10,color:"#9A9187",marginTop:5},dobRow:{flexDirection:"row",alignItems:"flex-end",gap:5},dobPart:{flex:1},yearPart:{flex:1.35},dobHint:{fontSize:9,color:"#9A9187",marginBottom:4,textAlign:"center"},slash:{fontSize:22,color:"#A99F93",paddingBottom:12},save:{backgroundColor:"#8C9670",borderRadius:999,paddingVertical:15,alignItems:"center",marginTop:20},saveText:{fontFamily:"Schoolbell_400Regular",fontSize:22,color:"#FFFDF8"},deleteButton:{paddingVertical:13,alignItems:"center",marginTop:10},deleteText:{fontSize:13,fontWeight:"800",color:"#B85F4A"},back:{textAlign:"center",marginTop:8,fontWeight:"700",color:"#756B60"}});