import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Coffee, Fish, Mountain, PartyPopper } from "@sketchyicons/react-native";
import { Point, RoutePrivacy, WalkTag } from "../types/walk";
import { hiddenEndsWillShowMap } from "../utils/routePrivacy";
import { formatTime } from "../utils/time";
import { WaltzMap } from "./WaltzMap";

export function defaultWalkTitle(date: Date) {
  const hour = Number(new Intl.DateTimeFormat("en-AU", {
    hour: "2-digit",
    hourCycle: "h23",
    timeZone: "Australia/Sydney",
  }).format(date));
  if (hour >= 5 && hour < 12) return "Morning waltz";
  if (hour >= 12 && hour < 18) return "Afternoon waltz";
  return "Night waltz";
}
type Props = { seconds:number; distance:number; points:Point[]; dogName:string; title:string; routePrivacy:RoutePrivacy; tags:WalkTag[]; isSaving:boolean; saveFailed:boolean; onTitleChange:(title:string)=>void; onTagsChange:(tags:WalkTag[])=>void; onRoutePrivacyChange:(privacy:RoutePrivacy)=>void; onSave:()=>void; onDiscard:()=>void };

export function WalkCompleteScreen({ seconds,distance,points,dogName,title,routePrivacy,tags,isSaving,saveFailed,onTitleChange,onTagsChange,onRoutePrivacyChange,onSave,onDiscard }: Props) {
  const toggleTag=(tag:WalkTag)=>onTagsChange(tags.includes(tag)?tags.filter((x)=>x!==tag):[...tags,tag]);

  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <View style={styles.titleRow}><Text style={styles.complete}>Walk complete!</Text><PartyPopper size={28} strokeWidth={2} color="#E87859" /></View>
    <View style={styles.metricsRow}><View><Text style={styles.metricLabel}>DISTANCE</Text><Text style={styles.resultDistance}>{distance.toFixed(2)} km</Text></View><View><Text style={styles.metricLabel}>TIME</Text><Text style={styles.resultTime}>{formatTime(seconds)}</Text></View></View>
    <View><Text style={styles.fieldLabel}>Activity title</Text><TextInput value={title} onChangeText={onTitleChange} maxLength={60} editable={!isSaving} placeholder={defaultWalkTitle(new Date())} selectTextOnFocus style={styles.titleInput}/></View>
    <View style={styles.mapWrap}>{points.length?<WaltzMap points={points} dogName={dogName} interactive/>:<View style={styles.noRoute}><Text style={styles.noRouteText}>No route points recorded for this walk.</Text></View>}</View>
    <View style={styles.tagsCard}><Text style={styles.shareTitle}>Add some tags</Text><Text style={styles.tagHint}>Optional. Pick anything that happened on this waltz.</Text><View style={styles.tagsRow}><Tag selected={tags.includes("trail")} disabled={isSaving} onPress={()=>toggleTag("trail")} icon={<Mountain size={20} strokeWidth={2}/>} label="Trail"/><Tag selected={tags.includes("swim")} disabled={isSaving} onPress={()=>toggleTag("swim")} icon={<Fish size={20} strokeWidth={2}/>} label="Gone fishing"/><Tag selected={tags.includes("coffee")} disabled={isSaving} onPress={()=>toggleTag("coffee")} icon={<Coffee size={20} strokeWidth={2}/>} label="Coffee stop"/></View></View>
    <View style={styles.shareCard}><View style={styles.shareCopyWrap}><Text style={styles.shareTitle}>Who can see this?</Text><Text style={styles.shareCopy}>Review your choice before saving. Stats only does not keep a map.</Text></View>
      {routePrivacy==="private"?<PrivacyChoice value="private" selected disabled={isSaving} title="Only me · Recovered walk" copy="This older private draft will stay off Feed unless you choose a sharing option below." onSelect={onRoutePrivacyChange}/>:null}
      <PrivacyChoice value="hidden_ends" selected={routePrivacy==="hidden_ends"} disabled={isSaving} title="Hide home area · Recommended" copy={hiddenEndsWillShowMap(points)?"Share the middle while hiding about 200 m at each end.":"This route is short, so Waltz will safely share stats without a map."} onSelect={onRoutePrivacyChange}/>
      <PrivacyChoice value="full" selected={routePrivacy==="full"} disabled={isSaving} title="Share full route" copy="Share every recorded route point, including the start and finish." onSelect={onRoutePrivacyChange}/>
      <PrivacyChoice value="stats_only" selected={routePrivacy==="stats_only"} disabled={isSaving} title="Share stats only" copy="Share distance, time and Boops. Your route stays private." onSelect={onRoutePrivacyChange}/>
    </View>
    {saveFailed?<View style={styles.saveError}><Text style={styles.saveErrorTitle}>Your walk is still safe</Text><Text style={styles.saveErrorCopy}>We couldn't save it just yet. Check your connection and try again.</Text></View>:null}
    <Pressable style={[styles.button,isSaving&&styles.buttonDisabled]} disabled={isSaving} onPress={onSave}>{isSaving?<View style={styles.savingRow}><ActivityIndicator color="#FFFDF8"/><Text style={styles.buttonText}>SAVING...</Text></View>:<Text style={styles.buttonText}>{saveFailed?"TRY SAVING AGAIN":"SAVE WALK"}</Text>}</Pressable><Pressable disabled={isSaving} onPress={onDiscard}><Text style={[styles.discard,isSaving&&styles.discardDisabled]}>Discard</Text></Pressable>
  </ScrollView></View>;
}
function Tag({selected,disabled,onPress,icon,label}:{selected:boolean;disabled:boolean;onPress:()=>void;icon:React.ReactNode;label:string}) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.tag,selected&&styles.tagSelected]}><View style={styles.tagIcon}>{icon}</View><Text style={[styles.tagText,selected&&styles.tagTextSelected]}>{label}</Text></Pressable>; }
function PrivacyChoice({value,selected,disabled,title,copy,onSelect}:{value:RoutePrivacy;selected:boolean;disabled:boolean;title:string;copy:string;onSelect:(value:RoutePrivacy)=>void}) { return <Pressable disabled={disabled} onPress={()=>onSelect(value)} style={[styles.privacyChoice,selected&&styles.privacyChoiceSelected]}><View style={[styles.radio,selected&&styles.radioSelected]}>{selected?<View style={styles.radioDot}/>:null}</View><View style={styles.privacyCopy}><Text style={styles.privacyTitle}>{title}</Text><Text style={styles.privacyHint}>{copy}</Text></View></Pressable>; }
const styles=StyleSheet.create({screen:{flex:1},content:{gap:10,paddingBottom:18},titleRow:{flexDirection:"row",alignItems:"center",gap:8},complete:{fontFamily:"Schoolbell_400Regular",fontSize:32,color:"#25211D"},metricsRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-end"},metricLabel:{fontSize:10,color:"#756B60",fontWeight:"800",marginBottom:3},resultDistance:{fontSize:36,fontWeight:"800",color:"#1D1A17"},resultTime:{fontSize:28,fontWeight:"800",color:"#1D1A17"},fieldLabel:{fontSize:10,fontWeight:"800",color:"#756B60",marginBottom:4},titleInput:{height:44,borderRadius:14,backgroundColor:"#FFFDF8",paddingHorizontal:13,fontSize:17,fontWeight:"800",color:"#1D1A17"},mapWrap:{height:210,borderRadius:24,overflow:"hidden",backgroundColor:"#EFE8DC"},noRoute:{flex:1,alignItems:"center",justifyContent:"center",padding:24},noRouteText:{color:"#756B60",textAlign:"center"},tagsCard:{backgroundColor:"#FFFDF8",borderRadius:20,padding:14,gap:8},tagHint:{fontSize:11,color:"#756B60"},tagsRow:{flexDirection:"row",flexWrap:"wrap",gap:8},tag:{flexDirection:"row",alignItems:"center",gap:5,paddingVertical:8,paddingHorizontal:10,borderRadius:999,backgroundColor:"#F1E7D7",borderWidth:1,borderColor:"transparent"},tagSelected:{backgroundColor:"#E6EAD9",borderColor:"#8C9670"},tagIcon:{width:21,alignItems:"center"},tagText:{fontSize:12,fontWeight:"700",color:"#655D54"},tagTextSelected:{color:"#596442"},shareCard:{backgroundColor:"#FFFDF8",borderRadius:20,padding:14,gap:8},shareCopyWrap:{gap:3,marginBottom:2},shareTitle:{fontSize:15,fontWeight:"800",color:"#1D1A17"},shareCopy:{fontSize:11,lineHeight:15,color:"#756B60"},privacyChoice:{flexDirection:"row",alignItems:"center",gap:10,borderWidth:1,borderColor:"#E5E0D8",borderRadius:12,padding:11},privacyChoiceSelected:{borderColor:"#8C9670",backgroundColor:"#F6F7F0"},radio:{width:18,height:18,borderRadius:9,borderWidth:1.5,borderColor:"#AAA197",alignItems:"center",justifyContent:"center"},radioSelected:{borderColor:"#78845C"},radioDot:{width:9,height:9,borderRadius:5,backgroundColor:"#78845C"},privacyCopy:{flex:1},privacyTitle:{fontSize:12,fontWeight:"800",color:"#332E29"},privacyHint:{fontSize:10,lineHeight:14,color:"#756B60",marginTop:2},saveError:{borderWidth:1,borderColor:"#D4A58F",borderRadius:14,backgroundColor:"#FFF8F3",padding:13},saveErrorTitle:{fontSize:13,fontWeight:"800",color:"#8D4F39"},saveErrorCopy:{fontSize:11,lineHeight:16,color:"#756B60",marginTop:3},button:{backgroundColor:"#8C9670",paddingVertical:15,borderRadius:999,alignItems:"center"},buttonDisabled:{opacity:.72},savingRow:{flexDirection:"row",alignItems:"center",gap:9},buttonText:{color:"#FFFDF8",fontFamily:"Schoolbell_400Regular",fontSize:23,letterSpacing:1.2},discard:{fontSize:14,textAlign:"center",color:"#756B60",textDecorationLine:"underline",paddingVertical:2},discardDisabled:{opacity:.45}});
